### PR TITLE
Order sections on homepage by weigth

### LINKED ISSUE #133: change location of projects section
Hi!
 
First of all thank you for creating this great theme.
Is it possible to change the order of the sections so that the projects section comes right after the about section?
Cant figure out how to do that.
Thank you very much in advance.

### PR DESCRIPTION
**Pull request by snow2k9**
Working weights for projects and blog section

Fixes #133

### CODE REVIEW

**Comment by snow2k9** [comment]
Sure, hope you meant those files

**Comment by hanzei** [comment]
Thanks. Would you also please update https://github.com/victoriadotdev/hugo-theme-introduction/blob/master/exampleSite/content/en/home/about.md and https://github.com/victoriadotdev/hugo-theme-introduction/blob/master/exampleSite/content/en/home/lorem.md?

**Comment by snow2k9** [comment]
Yep, sure, updated

**Comment by hanzei** [comment]
@snow2k9 Do you have any idea why one test run fails? See https://travis-ci.com/victoriadotdev/hugo-theme-introduction/jobs/191541624

**Comment by snow2k9** [comment]
Tried it with hugo 0.48 - seems the append function does not exists
```
ERROR 2019/04/10 11:09:04 Failed to add template "index.html" in path "index.html": template: index.html:50: function "append" not defined
ERROR 2019/04/10 11:09:04 index.html : template: index.html:50: function "append" not defined
INFO 2019/04/10 11:09:04 Using config file: /home/max/introduction/exampleSite/config.toml
Building sites … INFO 2019/04/10 11:09:04 syncing static files to /home/max/introduction/exampleSite/public/
INFO 2019/04/10 11:09:04 found taxonomies: map[string]string{"tag":"tags"}
INFO 2019/04/10 11:09:04 found taxonomies: map[string]string{"tag":"tags"}
INFO 2019/04/10 11:09:04 found taxonomies: map[string]string{"tag":"tags"}
INFO 2019/04/10 11:09:04 Alias "en" translated to "en/index.html"
ERROR 2019/04/10 11:09:04 Error while rendering "home" in "": template: "index.html" is an incomplete or empty template
```

**Comment by hanzei** [comment]
Well, we can drop support for Hugo 0.48. Please see https://github.com/victoriadotdev/hugo-theme-introduction/pull/147. Once this is merged, you can rebase your PR.

**Comment by hanzei** [comment]
Thanks for the PR @snow2k9! :tada:

**Comment by timpauli** [comment]
Hi!

First of all thanks a lot for creating this pull request!
WIth the current implementation there is a problem if you dont want a project or blog section and delete the folders because then you get:

```
execute of template failed: 
template: index.html:53:22: executing "index.html" at <.File.Dir>: 
error calling Dir: runtime error: invalid memory address or nil pointer dereference
```

**Comment by hanzei** [comment]
Thanks for the report @timpauli. @snow2k9 Do you want to fix this?

**Comment by snow2k9** [comment]
@hanzei if you want, sure
Im home in 3-4 hours

I think it's only a fileExists

**Comment by timpauli** [comment]
Thanks again for fixing this as well!

Another thing I came across is: the menu points at the top of the page now do not represent the weighted order of the sections. Which seems a bit odd to me. I would expect they appear from top to bottom like they appear from left to right in the menu bar.

**Pull request merged**
