### PR TITLE
Add space between social icons

### PR DESCRIPTION
**Pull request by tanohzana**
I had issues clicking on the icons, also, people around me told me it was annoying, so I added style to add more space between them.

Very few changes, but nice ones I believe.

### CODE REVIEW

**Comment by hanzei** [comment]
@tanohzana Thanks for the PR! Would you please share a before/after screenshot?

**Comment by tanohzana** [comment]
Sure ! There you go:

My site now:

Screenshot 2019-04-06 at 13 38 57

What the social links look like after:

Screenshot 2019-04-06 at 13 38 35

Same for the blog posts.

My site:

Screenshot 2019-04-06 at 13 39 22

What the social links look like after:

Screenshot 2019-04-06 at 13 39 38

**Comment by hanzei** [comment]
I like the look on the home page, but the space between the icons on the blog page looks to much to me. Would you mind reverting the changes for this page?

**Comment by tanohzana** [comment]
@hanzei should be good now ☺️

**Comment by hanzei** [comment]
@victoriadotdev Would you please review?

FYI: the netlify preview is broken.

**Comment by tanohzana** [comment]
I also added a light-grey background to code snippets, because I think it previously was hard to notice them between text blocks.

Here is a picture of before:

Screenshot 2019-04-14 at 09 40 07

And a picture of after:

Screenshot 2019-04-14 at 09 39 56

**Pull request merged**
