### PR TITLE
Fix sorted menu

### LINKED ISSUE #149: Menu doesn't respect weigth parameter
Another thing I came across is: The menu points at the top of the page now do not represent the weighted order of the sections. Which seems a bit odd to me. I would expect they appear from top to bottom like they appear from left to right in the menu bar.

_Originally posted by @timpauli in https://github.com/victoriadotdev/hugo-theme-introduction/pull/143#issuecomment-481880667_

### PR DESCRIPTION
**Pull request by snow2k9**
with this menu should respect weight

Fixes #149

### CODE REVIEW

**Comment by hanzei** [comment]
@timpauli Would you be open on testing this fix?

**Comment by timpauli** [comment]
fix works for me. thx a lot.

**Comment by snow2k9** [comment]
I think i fixed it.

But why is in blog section a permalink to /projects but on home theres no link to /projects

**Comment by hanzei** [comment]
> But why is in blog section a permalink to /projects but on home theres no link to /projects

Could you elaborate? I don't get what you are referring to.

**Comment by timpauli** [comment]
nonetheless merge?

**Comment by snow2k9** [comment]
@hanzei 
On Home "Projects" links to `#projects`
On /blog "Projects" links to `/projects`
See https://hugo-introduction.netlify.com/blog/

**Pull request merged**
