### PR TITLE
File context warning fixed

### PR DESCRIPTION
**Pull request by martinhoefling**
Hugo complains about .File.Dir not being used with "with" or in if context.

### CODE REVIEW

**Comment by hanzei** [comment]
What version of Hugo does show this warning? I don't see it on `v0.55.5`.

**Comment by martinhoefling** [comment]
0.55.4 installed via brew

**Comment by martinhoefling** [comment]
Let me check out with 0.55.5 and if this doesn’t fix the warning, I provide a minimal example.

**Comment by martinhoefling** [comment]
Checked with 0.55.5 and the warning disappeared.

**Comment by martinhoefling** [comment]
@hanzei  I checked it again and it still shows up if I do not have this patch applied

**Comment by hanzei** [comment]
Could you share a bit more information? What hugo version are you using? What os?  What command did you run? What is the output you seed?

**Comment by martinhoefling** [comment]
╰─ hugo version
Hugo Static Site Generator v0.55.5/extended darwin/amd64 BuildDate: unknown

Installed via brew on OSX Mojave (10.14.4)

```
╰─ hugo                       
Building sites … WARN 2019/05/12 22:09:44 .File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}
WARN 2019/05/12 22:09:44 .File.TranslationBaseName on zero object. Wrap it in if or with: {{ with .File }}{{ .TranslationBaseName }}{{ end }}

                   | DE  | EN   
+------------------+-----+-----+
  Pages            | 102 | 127  
  Paginator pages  |   0 |   0  
  Non-page files   |  25 |  26  
  Static files     |  59 |  59  
  Processed images |   0 |   0  
  Aliases          |  46 |  48  
  Sitemaps         |   2 |   1  
  Cleaned          |   0 |   0  

Total in 1252 ms

```

**Comment by hanzei** [comment]
Hm, interesting. I don't see a problem with merging this.

**Comment by martinhoefling** [comment]
Thx!

**Pull request merged**
